Repository onegyeol/GNUB, pull requests merged in 2024-10, with the labels that each got.

#1 Feat: 로그인(1)
  src/main/java/pbl/GNUB/config/DepartmentDataInitializer.java
  src/main/java/pbl/GNUB/entity/College.java
  src/main/java/pbl/GNUB/entity/Department.java
  src/main/java/pbl/GNUB/entity/Member.java
  src/main/java/pbl/GNUB/repository/DepartmentRepository.java
  src/main/java/pbl/GNUB/service/MemberService.java
Labels: function

#3 Feat: html 페이지 업로드
  src/main/resources/templates/form/board.html
  src/main/resources/templates/form/foodDetails.html
  src/main/resources/templates/form/keepList.html
  src/main/resources/templates/form/likeList.html
  src/main/resources/templates/form/main.html
  src/main/resources/templates/form/myPage.html
  src/main/resources/templates/form/myPost.html
  src/main/resources/templates/form/post.html
  src/main/resources/templates/form/search.html
  src/main/resources/templates/form/write.html
Labels: html

#4 Feat: static 경로 file 업로드
  src/main/resources/static/css/.DS_Store
  src/main/resources/static/css/component/sorting.css
  src/main/resources/static/css/foodDetails.css
  src/main/resources/static/css/root.css
  src/main/resources/static/css/screen/board.css
  src/main/resources/static/css/screen/post.css
  src/main/resources/static/css/screen/search.css
  src/main/resources/static/css/screen/srp.css
  src/main/resources/static/css/screen/write.css
  src/main/resources/static/css/style.css
  src/main/resources/static/csv/shop.csv
  src/main/resources/static/image/gnub_logo.png
  src/main/resources/static/image/restaurant.jpg
  src/main/resources/static/image/restaurant2.jpg
  src/main/resources/static/image/searching-icon.png
  src/main/resources/static/javascript/main.js
  src/main/resources/static/javascript/script.js
  src/main/resources/static/javascript/search.js
Labels: function

#5 Feat: url 매핑 컨트롤러
  src/main/java/pbl/GNUB/controller/BoardController.java
  src/main/java/pbl/GNUB/controller/MainController.java
  src/main/java/pbl/GNUB/controller/MemberController.java
  src/main/java/pbl/GNUB/controller/MypageController.java
Labels: function

#6 Feat: 로그인, 회원가입 (2)
  src/main/resources/static/css/join.css
  src/main/resources/static/css/login.css
  src/main/resources/static/javascript/join.js
  src/main/resources/static/javascript/login.js
  src/main/resources/static/text/이용약관1.txt
  src/main/resources/static/text/이용약관2.txt
  src/main/resources/templates/form/join.html
  src/main/resources/templates/form/login.html
Labels: function

#7 Feat: 음식점 csv 파일 -> mysql 테이블 생성
  build.gradle
  src/main/java/pbl/GNUB/config/JobConfiguration.java
  src/main/java/pbl/GNUB/controller/MainController.java
  src/main/java/pbl/GNUB/csv/CsvShopReader.java
  src/main/java/pbl/GNUB/csv/CsvShopWriter.java
  src/main/java/pbl/GNUB/dto/ShopDto.java
  src/main/java/pbl/GNUB/entity/Shop.java
  src/main/java/pbl/GNUB/repository/ShopRepository.java
  src/main/resources/application.properties
  src/main/resources/spring-batch/schema-mysql.sql
  src/main/resources/static/csv/shop.csv
Labels: function

#8 Fix: 게시판 작성 화면 수정
  src/main/resources/static/css/screen/write.css
  src/main/resources/static/css/summernote/font/summernote.eot
  src/main/resources/static/css/summernote/font/summernote.hash
  src/main/resources/static/css/summernote/font/summernote.ttf
  src/main/resources/static/css/summernote/font/summernote.woff
  src/main/resources/static/css/summernote/font/summernote.woff2
  src/main/resources/static/css/summernote/summernote-lite.css
  src/main/resources/templates/form/write.html
Labels: function

#9 Feat: 좋아요 기능
  src/main/java/pbl/GNUB/entity/Like.java
Labels: function

#12 Feat : 로그인/회원가입 기능
  src/main/java/pbl/GNUB/config/SecurityConfig.java
  src/main/java/pbl/GNUB/controller/MemberController.java
  src/main/java/pbl/GNUB/dto/MemberFormDto.java
  src/main/java/pbl/GNUB/entity/Member.java
  src/main/java/pbl/GNUB/repository/DepartmentRepository.java
  src/main/java/pbl/GNUB/repository/MemberRepository.java
  src/main/java/pbl/GNUB/service/MemberService.java
  src/main/resources/templates/form/login.html
  src/main/resources/templates/form/main.html
Labels: function

#14 Fix : 로그인/회원가입 오류 수정
  src/main/java/pbl/GNUB/GnubApplication.java
  src/main/java/pbl/GNUB/config/SecurityConfig.java
  src/main/java/pbl/GNUB/controller/LikeController.java
  src/main/java/pbl/GNUB/controller/MemberController.java
  src/main/java/pbl/GNUB/dto/LikeDto.java
  src/main/java/pbl/GNUB/dto/MemberFormDto.java
  src/main/java/pbl/GNUB/repository/LikeRepository.java
  src/main/java/pbl/GNUB/service/LikeService.java
  src/main/java/pbl/GNUB/service/MemberService.java
  src/main/resources/templates/form/board.html
  src/main/resources/templates/form/foodDetails.html
  src/main/resources/templates/form/likeList.html
  src/main/resources/templates/form/main.html
  src/main/resources/templates/form/post.html
  src/main/resources/templates/form/search.html
  src/main/resources/templates/form/write.html
Labels: bug

#15 Feat : 좋아요 기능(2)
  src/main/java/pbl/GNUB/controller/LikeController.java
  src/main/java/pbl/GNUB/controller/MypageController.java
  src/main/java/pbl/GNUB/dto/LikeDto.java
  src/main/java/pbl/GNUB/entity/Like.java
  src/main/java/pbl/GNUB/entity/Shop.java
  src/main/java/pbl/GNUB/repository/LikeRepository.java
  src/main/java/pbl/GNUB/repository/MemberRepository.java
  src/main/java/pbl/GNUB/service/LikeService.java
  src/main/resources/templates/form/main.html
Labels: function

#18 Feat : 게시판 기능
  src/main/java/pbl/GNUB/controller/BoardController.java
  src/main/java/pbl/GNUB/dto/BoardDTO.java
  src/main/java/pbl/GNUB/entity/BaseEntity.java
  src/main/java/pbl/GNUB/entity/Board.java
  src/main/java/pbl/GNUB/repository/BoardRepository.java
  src/main/java/pbl/GNUB/service/MemberServiceImpl.java
  src/main/resources/templates/form/board.html
  src/main/resources/templates/form/write.html
Labels: function

#19 Feat : BoardService
  src/main/java/pbl/GNUB/service/BoardService.java
Labels: function

#20 Feat : member entity
  src/main/java/pbl/GNUB/entity/Member.java
Labels: function

#21 Feat : 게시판 작성 기능 (2)
  src/main/java/pbl/GNUB/config/SecurityConfig.java
  src/main/java/pbl/GNUB/controller/BoardController.java
  src/main/java/pbl/GNUB/dto/BoardDto.java
  src/main/java/pbl/GNUB/entity/Board.java
  src/main/java/pbl/GNUB/service/BoardService.java
  src/main/resources/templates/form/board.html
  src/main/resources/templates/form/foodDetails.html
  src/main/resources/templates/form/join.html
  src/main/resources/templates/form/keepList.html
  src/main/resources/templates/form/likeList.html
  src/main/resources/templates/form/main.html
  src/main/resources/templates/form/myPage.html
  src/main/resources/templates/form/myPost.html
  src/main/resources/templates/form/post.html
  src/main/resources/templates/form/search.html
  src/main/resources/templates/form/write.html
Labels: function

#22 Feat : 메인화면/음식점 상세 정보 기능
  src/main/java/pbl/GNUB/controller/MainController.java
  src/main/java/pbl/GNUB/repository/ShopRepository.java
  src/main/java/pbl/GNUB/service/ShopService.java
  src/main/resources/static/javascript/script.js
  src/main/resources/templates/form/main.html
Labels: function

#24 Feat : 음식점 태그
  src/main/java/pbl/GNUB/csv/CsvShopTagReader.java
  src/main/java/pbl/GNUB/csv/CsvShopTagWriter.java
  src/main/java/pbl/GNUB/dto/ShopTagDto.java
  src/main/java/pbl/GNUB/entity/ShopTag.java
Labels: function
